image:
  file: .gitpod.Dockerfile

tasks:
  - init: pip install textual
    command: doppler setup --no-interactive && doppler run --mount /home/gitpod/.aws/credentials --mount-template aws-creds -- doppler run --mount /home/gitpod/.aws/config --mount-template aws-conf -- python3 cli.py